/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { MassageService } from './services/massage.service';
export { ChatService } from './services/chat.service';
export { UserService } from './services/user.service';
